name: Build and Push Images
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - service: nginx
            dockerfile: ./nginx/Dockerfile
            context: ./nginx
            image: uladdzerzh/nginx
          - service: php
            dockerfile: ./html/Dockerfile
            context: ./html
            image: uladdzerzh/html
          - service: mysql
            dockerfile: ./mysql/Dockerfile
            context: ./mysql
            image: uladdzerzh/mysql

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker buildx build --platform ${{ matrix.arch }} -t ${{ matrix.image }} -f ${{ matrix.dockerfile }} {{ defaultContext }}:${{ matrix.context }}
          docker push ${{ matrix.image }}