name: Build and Push Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [linux/amd64, linux/arm64]
        include:
          - service: nginx
            dockerfile: Dockerfile_nginx
            context: .
            image: uladdzerzh/nginx
          - service: phpfpm
            dockerfile: Dockerfile_php
            context: .
            image: uladdzerzh/phpfpm
          - service: mysql
            dockerfile: Dockerfile_mysql
            context: .
            image: uladdzerzh/mysql

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: |
          docker buildx create --use
          docker buildx build --platform ${{ matrix.arch }} --push -t ${{ matrix.service.image }} -f ${{ matrix.service.dockerfile }} ./${{ matrix.service.context }}